Second trial to create a pull request
tj-devel709/InternPlayground pull request #18
Opened 2022-06-21 22:33 UTC by gal42

Created a file with my favorite movie

2022-06-21 23:10 UTC, rachelkang requested changes
Awesome job!!

One small suggestion I have - could you move this file so that it's inside the GalExample directory? And then delete the trail2 directory since it will be empty

2022-06-21 23:10 UTC, rachelkang commented on trial2/text2.txt
> +My favorite movie is Big Hero 6
A great movie!!

2022-06-21 23:28 UTC, gal42 commented on trial2/text2.txt
> +My favorite movie is Big Hero 6
Hi Rachel! I this I successfully moved the file and deleted the directory!

2022-06-22 13:43 UTC, rachelkang commented on trial2/text2.txt
> +My favorite movie is Big Hero 6
Awesome - great job!

2022-06-22 13:44 UTC, rachelkang approved these changes
LGTM!

One more nit suggestion for the future - remember to rename the file so that it is relevant to the content it holds. For the purpose of this exericse, however, this is great!

2022-06-22 16:10 UTC, tj-devel709 approved these changes

2022-06-22 16:11 UTC, merged